{"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/pullrequests/27/comments/73065103.json"}, "code": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/genomedata/diff/mjmm13/genomedata-py2_3-test:4233257e4981..0bb1dda3fc3d?path=setup.py"}, "html": {"href": "#!/hoffmanlab/genomedata/pull-requests/27/_/diff#comment-73065103"}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 27, "links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/pullrequests/27.json"}, "html": {"href": "#!/hoffmanlab/genomedata/pull-requests/27"}}, "title": "Pipeline Update and Python 3 Compatibility"}, "content": {"raw": "Why catch the OSError? What specifically are you trying to catch and ignore here? Could you add a comment to the code here as well to be explicit that the specific exceptions are expected and should be ignored?", "markup": "markdown", "html": "<p>Why catch the OSError? What specifically are you trying to catch and ignore here? Could you add a comment to the code here as well to be explicit that the specific exceptions are expected and should be ignored?</p>", "type": "rendered"}, "created_on": "2018-08-15T18:17:41.862933+00:00", "user": {"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}, "inline": {"to": 127, "from": null, "outdated": true, "path": "setup.py"}, "updated_on": "2018-08-15T18:17:41.870471+00:00", "type": "pullrequest_comment", "id": 73065103}