{"pagelen": 50, "values": [{"update": {"description": "Hi,\r\n\r\nI created a test chr1.fa file matching the example [here](https://www.pmgenomics.ca/hoffmanlab/proj/genomedata/doc/1.3.6/genomedata.html#example). When I run the genomedata-load-seq command:\r\n\r\n```\r\n#!shell\r\n\r\ngenomedata-load-seq genomedata.test chr1.fa\r\n```\r\n\r\nI get the following error:\r\n\r\n```\r\n#!shell\r\n\r\nTraceback (most recent call last):\r\n  File \"/net/noble/vol2/home/katecook/.local/bin/genomedata-load-seq\", line 11, in <module>\r\n    sys.exit(main())\r\n  File \"/net/noble/vol2/home/katecook/.local/lib/python2.7/site-packages/genomedata/_load_seq.py\", line 318, in main\r\n    mode=args.mode, seqfile_type=args.seqfile_type)\r\n  File \"/net/noble/vol2/home/katecook/.local/lib/python2.7/site-packages/genomedata/_load_seq.py\", line 250, in load_seq\r\n    assert seqfile_type in frozenset([\"agp\", \"fasta\"])\r\nAssertionError\r\n```\r\n\r\nLooking at the code, the problem seems to be that the argument seqfile_type gets set to None. Adding a default=\"fasta\" option to the --assembly argument fixes the bug, but I admit I am not entirely sure why, since it should get set to that default by the --sizes argument.\r\n\r\nVersions of things:\r\n\r\nPython 2.7.3\r\nnumpy 1.11.0\r\npytables 3.3.0\r\nhdf5 1.8.18\r\nsegway 1.4.1", "title": "Fix assertion failure on argument parsing when loading fasta sequence", "destination": {"commit": {"hash": "dceca0d8f602", "type": "commit", "links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/commit/dceca0d8f602.json"}, "html": {"href": "#!/hoffmanlab/genomedata/commits/dceca0d8f602"}}}, "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata.json"}, "html": {"href": "#!/hoffmanlab/genomedata"}, "avatar": {"href": "data/bytebucket.org/ravatar/{78038659-1199-46ff-9d0a-675c62f89d60}ts=python"}}, "type": "repository", "name": "genomedata", "full_name": "hoffmanlab/genomedata", "uuid": "{78038659-1199-46ff-9d0a-675c62f89d60}"}, "branch": {"name": "default"}}, "reason": "", "source": {"commit": {"hash": "73347b435c7d", "type": "commit", "links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/katecook/genomedata/commit/73347b435c7d"}, "html": {"href": "https://bitbucket.org/katecook/genomedata/commits/73347b435c7d"}}}, "repository": {"links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/katecook/genomedata"}, "html": {"href": "https://bitbucket.org/katecook/genomedata"}, "avatar": {"href": "data/bytebucket.org/ravatar/{8125d01a-ff83-41a9-a745-97ee1d304ed8}ts=python"}}, "type": "repository", "name": "genomedata", "full_name": "katecook/genomedata", "uuid": "{8125d01a-ff83-41a9-a745-97ee1d304ed8}"}, "branch": {"name": "default"}}, "state": "MERGED", "author": {"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}, "date": "2017-01-09T15:58:53.625954+00:00"}, "pull_request": {"type": "pullrequest", "id": 16, "links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/pullrequests/16.json"}, "html": {"href": "#!/hoffmanlab/genomedata/pull-requests/16"}}, "title": "Fix assertion failure on argument parsing when loading fasta sequence"}}, {"approval": {"date": "2017-01-09T15:56:01.350841+00:00", "pullrequest": {"type": "pullrequest", "id": 16, "links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/pullrequests/16.json"}, "html": {"href": "#!/hoffmanlab/genomedata/pull-requests/16"}}, "title": "Fix assertion failure on argument parsing when loading fasta sequence"}, "user": {"display_name": "Michael Hoffman", "uuid": "{ffa8e039-5d4d-4f69-a4ba-ac25cbaf700b}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bffa8e039-5d4d-4f69-a4ba-ac25cbaf700b%7D"}, "html": {"href": "https://bitbucket.org/%7Bffa8e039-5d4d-4f69-a4ba-ac25cbaf700b%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/6a95e857a02504cbad5fe965c9d9e4bbd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsMH-1.png"}}, "nickname": "hoffman", "type": "user", "account_id": "557058:a9657985-692c-405c-995b-4e41cda7ba2b"}}, "pull_request": {"type": "pullrequest", "id": 16, "links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/pullrequests/16.json"}, "html": {"href": "#!/hoffmanlab/genomedata/pull-requests/16"}}, "title": "Fix assertion failure on argument parsing when loading fasta sequence"}}, {"comment": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/pullrequests/16/comments/29302017.json"}, "html": {"href": "#!/hoffmanlab/genomedata/pull-requests/16/_/diff#comment-29302017"}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 16, "links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/pullrequests/16.json"}, "html": {"href": "#!/hoffmanlab/genomedata/pull-requests/16"}}, "title": "Fix assertion failure on argument parsing when loading fasta sequence"}, "content": {"raw": "I confirmed that seqfile_type is being set to `None` by default. The `default` argument in for each add_argument is presumed to be `None`. It could be the case that when the arguments get parsed (parse_args), they do not get parsed in the order they are added. This load sequence bug could be a bug from all the way on revision 0b39771b07e1 since this interface is not commonly used.\n\nThanks for the catch!\n", "markup": "markdown", "html": "<p>I confirmed that seqfile_type is being set to <code>None</code> by default. The <code>default</code> argument in for each add_argument is presumed to be <code>None</code>. It could be the case that when the arguments get parsed (parse_args), they do not get parsed in the order they are added. This load sequence bug could be a bug from all the way on revision <a href=\"#!/hoffmanlab/genomedata/commits/0b39771b07e1\" rel=\"nofollow\" class=\"ap-connect-link\">0b39771b07e1</a> since this interface is not commonly used.</p>\n<p>Thanks for the catch!</p>", "type": "rendered"}, "created_on": "2017-01-06T18:49:41.345782+00:00", "user": {"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}, "updated_on": "2017-01-06T18:49:41.349137+00:00", "type": "pullrequest_comment", "id": 29302017}, "pull_request": {"type": "pullrequest", "id": 16, "links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/pullrequests/16.json"}, "html": {"href": "#!/hoffmanlab/genomedata/pull-requests/16"}}, "title": "Fix assertion failure on argument parsing when loading fasta sequence"}}, {"approval": {"date": "2017-01-06T18:48:56.043621+00:00", "pullrequest": {"type": "pullrequest", "id": 16, "links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/pullrequests/16.json"}, "html": {"href": "#!/hoffmanlab/genomedata/pull-requests/16"}}, "title": "Fix assertion failure on argument parsing when loading fasta sequence"}, "user": {"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}}, "pull_request": {"type": "pullrequest", "id": 16, "links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/pullrequests/16.json"}, "html": {"href": "#!/hoffmanlab/genomedata/pull-requests/16"}}, "title": "Fix assertion failure on argument parsing when loading fasta sequence"}}, {"update": {"description": "Hi,\r\n\r\nI created a test chr1.fa file matching the example [here](https://www.pmgenomics.ca/hoffmanlab/proj/genomedata/doc/1.3.6/genomedata.html#example). When I run the genomedata-load-seq command:\r\n\r\n```\r\n#!shell\r\n\r\ngenomedata-load-seq genomedata.test chr1.fa\r\n```\r\n\r\nI get the following error:\r\n\r\n```\r\n#!shell\r\n\r\nTraceback (most recent call last):\r\n  File \"/net/noble/vol2/home/katecook/.local/bin/genomedata-load-seq\", line 11, in <module>\r\n    sys.exit(main())\r\n  File \"/net/noble/vol2/home/katecook/.local/lib/python2.7/site-packages/genomedata/_load_seq.py\", line 318, in main\r\n    mode=args.mode, seqfile_type=args.seqfile_type)\r\n  File \"/net/noble/vol2/home/katecook/.local/lib/python2.7/site-packages/genomedata/_load_seq.py\", line 250, in load_seq\r\n    assert seqfile_type in frozenset([\"agp\", \"fasta\"])\r\nAssertionError\r\n```\r\n\r\nLooking at the code, the problem seems to be that the argument seqfile_type gets set to None. Adding a default=\"fasta\" option to the --assembly argument fixes the bug, but I admit I am not entirely sure why, since it should get set to that default by the --sizes argument.\r\n\r\nVersions of things:\r\n\r\nPython 2.7.3\r\nnumpy 1.11.0\r\npytables 3.3.0\r\nhdf5 1.8.18\r\nsegway 1.4.1", "title": "Fix assertion failure on argument parsing when loading fasta sequence", "destination": {"commit": {"hash": "dceca0d8f602", "type": "commit", "links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/commit/dceca0d8f602.json"}, "html": {"href": "#!/hoffmanlab/genomedata/commits/dceca0d8f602"}}}, "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata.json"}, "html": {"href": "#!/hoffmanlab/genomedata"}, "avatar": {"href": "data/bytebucket.org/ravatar/{78038659-1199-46ff-9d0a-675c62f89d60}ts=python"}}, "type": "repository", "name": "genomedata", "full_name": "hoffmanlab/genomedata", "uuid": "{78038659-1199-46ff-9d0a-675c62f89d60}"}, "branch": {"name": "default"}}, "reason": "", "source": {"commit": {"hash": "73347b435c7d", "type": "commit", "links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/katecook/genomedata/commit/73347b435c7d"}, "html": {"href": "https://bitbucket.org/katecook/genomedata/commits/73347b435c7d"}}}, "repository": {"links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/katecook/genomedata"}, "html": {"href": "https://bitbucket.org/katecook/genomedata"}, "avatar": {"href": "data/bytebucket.org/ravatar/{8125d01a-ff83-41a9-a745-97ee1d304ed8}ts=python"}}, "type": "repository", "name": "genomedata", "full_name": "katecook/genomedata", "uuid": "{8125d01a-ff83-41a9-a745-97ee1d304ed8}"}, "branch": {"name": "default"}}, "state": "OPEN", "author": {"display_name": "Kate Cook", "uuid": "{36c88b70-42d6-4662-bde3-2316c4423895}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B36c88b70-42d6-4662-bde3-2316c4423895%7D"}, "html": {"href": "https://bitbucket.org/%7B36c88b70-42d6-4662-bde3-2316c4423895%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/f46c0bafb4d227957572a7f47c9e2980d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsKC-4.png"}}, "nickname": "katecook", "type": "user", "account_id": "557058:499caa63-3f6a-4f40-b404-8fc921427fc9"}, "date": "2017-01-06T01:12:38.022028+00:00"}, "pull_request": {"type": "pullrequest", "id": 16, "links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/pullrequests/16.json"}, "html": {"href": "#!/hoffmanlab/genomedata/pull-requests/16"}}, "title": "Fix assertion failure on argument parsing when loading fasta sequence"}}, {"update": {"description": "Hi,\r\n\r\nI created a test chr1.fa file matching the example [here](https://www.pmgenomics.ca/hoffmanlab/proj/genomedata/doc/1.3.6/genomedata.html#example). When I run the genomedata-load-seq command:\r\n\r\n```\r\n#!shell\r\n\r\ngenomedata-load-seq genomedata.test chr1.fa\r\n```\r\n\r\nI get the following error:\r\n\r\n```\r\n#!shell\r\n\r\nTraceback (most recent call last):\r\n  File \"/net/noble/vol2/home/katecook/.local/bin/genomedata-load-seq\", line 11, in <module>\r\n    sys.exit(main())\r\n  File \"/net/noble/vol2/home/katecook/.local/lib/python2.7/site-packages/genomedata/_load_seq.py\", line 318, in main\r\n    mode=args.mode, seqfile_type=args.seqfile_type)\r\n  File \"/net/noble/vol2/home/katecook/.local/lib/python2.7/site-packages/genomedata/_load_seq.py\", line 250, in load_seq\r\n    assert seqfile_type in frozenset([\"agp\", \"fasta\"])\r\nAssertionError\r\n```\r\n\r\nLooking at the code, the problem seems to be that the argument seqfile_type gets set to None. Adding a default=\"fasta\" option to the --assembly argument fixes the bug, but I admit I am not entirely sure why, since it should get set to that default by the --sizes argument.\r\n\r\nVersions of things:\r\n\r\nPython 2.7.3\r\nnumpy 1.11.0\r\npytables 3.3.0\r\nhdf5 1.8.18\r\nsegway 1.4.1", "title": "Fix assertion failure on argument parsing when loading fasta sequence", "destination": {"commit": {"hash": "dceca0d8f602", "type": "commit", "links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/commit/dceca0d8f602.json"}, "html": {"href": "#!/hoffmanlab/genomedata/commits/dceca0d8f602"}}}, "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata.json"}, "html": {"href": "#!/hoffmanlab/genomedata"}, "avatar": {"href": "data/bytebucket.org/ravatar/{78038659-1199-46ff-9d0a-675c62f89d60}ts=python"}}, "type": "repository", "name": "genomedata", "full_name": "hoffmanlab/genomedata", "uuid": "{78038659-1199-46ff-9d0a-675c62f89d60}"}, "branch": {"name": "default"}}, "reason": "", "source": {"commit": {"hash": "73347b435c7d", "type": "commit", "links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/katecook/genomedata/commit/73347b435c7d"}, "html": {"href": "https://bitbucket.org/katecook/genomedata/commits/73347b435c7d"}}}, "repository": {"links": {"self": {"href": "https://api.bitbucket.org/2.0/repositories/katecook/genomedata"}, "html": {"href": "https://bitbucket.org/katecook/genomedata"}, "avatar": {"href": "data/bytebucket.org/ravatar/{8125d01a-ff83-41a9-a745-97ee1d304ed8}ts=python"}}, "type": "repository", "name": "genomedata", "full_name": "katecook/genomedata", "uuid": "{8125d01a-ff83-41a9-a745-97ee1d304ed8}"}, "branch": {"name": "default"}}, "state": "OPEN", "author": {"display_name": "Kate Cook", "uuid": "{36c88b70-42d6-4662-bde3-2316c4423895}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B36c88b70-42d6-4662-bde3-2316c4423895%7D"}, "html": {"href": "https://bitbucket.org/%7B36c88b70-42d6-4662-bde3-2316c4423895%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/f46c0bafb4d227957572a7f47c9e2980d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsKC-4.png"}}, "nickname": "katecook", "type": "user", "account_id": "557058:499caa63-3f6a-4f40-b404-8fc921427fc9"}, "date": "2017-01-06T01:12:38.000812+00:00"}, "pull_request": {"type": "pullrequest", "id": 16, "links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/pullrequests/16.json"}, "html": {"href": "#!/hoffmanlab/genomedata/pull-requests/16"}}, "title": "Fix assertion failure on argument parsing when loading fasta sequence"}}]}