{"priority": "minor", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata.json"}, "html": {"href": "#!/hoffmanlab/genomedata"}, "avatar": {"href": "data/bytebucket.org/ravatar/{78038659-1199-46ff-9d0a-675c62f89d60}ts=python"}}, "type": "repository", "name": "genomedata", "full_name": "hoffmanlab/genomedata", "uuid": "{78038659-1199-46ff-9d0a-675c62f89d60}"}, "links": {"attachments": {"href": "data/repositories/hoffmanlab/genomedata/issues/26/attachments_page=1.json"}, "self": {"href": "data/repositories/hoffmanlab/genomedata/issues/26.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/genomedata/issues/26/watch"}, "comments": {"href": "data/repositories/hoffmanlab/genomedata/issues/26/comments_page=1.json"}, "html": {"href": "#!/hoffmanlab/genomedata/issues/26/accessing-track-dependent-attributes-of"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/genomedata/issues/26/vote"}}, "reporter": {"display_name": "Coby Viner", "uuid": "{5c0277b2-d18f-432a-9ff0-3377d3063bd6}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B5c0277b2-d18f-432a-9ff0-3377d3063bd6%7D"}, "html": {"href": "https://bitbucket.org/%7B5c0277b2-d18f-432a-9ff0-3377d3063bd6%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/30ee4699432a3591c043fbe3d4bff771d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCV-5.png"}}, "nickname": "cviner2", "type": "user", "account_id": "557058:278c659b-177a-486c-bf20-6982986d7e43"}, "title": "Accessing track-dependent attributes of archives without any tracks results in a fatal error", "component": null, "votes": 0, "watches": 2, "content": {"raw": "While Genomedata archives can be [created without any tracks](#!/hoffmanlab/genomedata/commits/8cdae6fd4fcf3e23076d63862fa8d441c216a27f), attempting to access any track-related attributes for such archives fails with a somewhat cryptic error, instead of (ideally) returning empty attributes or a clear error message.\r\n\r\nAttempting to access track attributes, via either the command-line interface or Python API, fails, eventually resulting in an error in the `__getattr__` method of `tables/attributeset.py`:\r\n\r\n```\r\n    \"'%s'\" % (name, self._v__nodepath))\r\nAttributeError: Attribute 'tracknames' does not exist in node: '/'\r\n```\r\n\r\nThis error can be easily reproduced by invoking `genomedata-info tracknames <archive>`, while `genomedata-info sizes <archive>` results in the expected output. This also occurs with other track-dependent attributes, such as `num_tracks_continuous` or `vars`, accessible from the Python API.\r\n\r\nThis appears to occur due to Genomedata archives without tracks not having any track-dependent attributes, like `num_tracks_continuous`. Refer to the enclosed file, containing Python output, listing all attributes of a loaded Genomedata archive without any tracks (the result of\r\n`pprint(genome.__dict__)`, in which `genome = Genome(<archive>)`. \r\n\r\nIdeally, such archives should still contain all track-related attributes, initialized to their standard empty values, such as `num_tracks_continuous = 0` and `vars = np.array([])`.", "markup": "markdown", "html": "<p>While Genomedata archives can be <a data-is-external-link=\"true\" href=\"#!/hoffmanlab/genomedata/commits/8cdae6fd4fcf3e23076d63862fa8d441c216a27f\" rel=\"nofollow\">created without any tracks</a>, attempting to access any track-related attributes for such archives fails with a somewhat cryptic error, instead of (ideally) returning empty attributes or a clear error message.</p>\n<p>Attempting to access track attributes, via either the command-line interface or Python API, fails, eventually resulting in an error in the <code>__getattr__</code> method of <code>tables/attributeset.py</code>:</p>\n<div class=\"codehilite\"><pre><span></span>    &quot;&#39;%s&#39;&quot; % (name, self._v__nodepath))\nAttributeError: Attribute &#39;tracknames&#39; does not exist in node: &#39;/&#39;\n</pre></div>\n\n\n<p>This error can be easily reproduced by invoking <code>genomedata-info tracknames &lt;archive&gt;</code>, while <code>genomedata-info sizes &lt;archive&gt;</code> results in the expected output. This also occurs with other track-dependent attributes, such as <code>num_tracks_continuous</code> or <code>vars</code>, accessible from the Python API.</p>\n<p>This appears to occur due to Genomedata archives without tracks not having any track-dependent attributes, like <code>num_tracks_continuous</code>. Refer to the enclosed file, containing Python output, listing all attributes of a loaded Genomedata archive without any tracks (the result of\n<code>pprint(genome.__dict__)</code>, in which <code>genome = Genome(&lt;archive&gt;)</code>. </p>\n<p>Ideally, such archives should still contain all track-related attributes, initialized to their standard empty values, such as <code>num_tracks_continuous = 0</code> and <code>vars = np.array([])</code>.</p>", "type": "rendered"}, "assignee": {"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}, "state": "open", "version": null, "edited_on": null, "created_on": "2016-09-22T23:17:38.066682+00:00", "milestone": null, "updated_on": "2019-07-06T18:26:05.305711+00:00", "type": "issue", "id": 26}