{"priority": "minor", "kind": "enhancement", "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata.json"}, "html": {"href": "#!/hoffmanlab/genomedata"}, "avatar": {"href": "data/bytebucket.org/ravatar/{78038659-1199-46ff-9d0a-675c62f89d60}ts=python"}}, "type": "repository", "name": "genomedata", "full_name": "hoffmanlab/genomedata", "uuid": "{78038659-1199-46ff-9d0a-675c62f89d60}"}, "links": {"attachments": {"href": "data/repositories/hoffmanlab/genomedata/issues/28/attachments_page=1.json"}, "self": {"href": "data/repositories/hoffmanlab/genomedata/issues/28.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/genomedata/issues/28/watch"}, "comments": {"href": "data/repositories/hoffmanlab/genomedata/issues/28/comments_page=1.json"}, "html": {"href": "#!/hoffmanlab/genomedata/issues/28/better-error-message-when-genomedata-load"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/genomedata/issues/28/vote"}}, "reporter": {"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}, "title": "Better error message when genomedata-load is not on the PATH", "component": null, "votes": 0, "watches": 1, "content": {"raw": "Currently there is an error on line 79 in _load_data.py where if genomedata-load is not on your path, python attempts to pipe into a process it cannot find resulting in a \"write error: Broken pipe\" and \"OSError: [Errno 2] No such file or directory\".\r\n\r\nThere should be a better error message for this case.", "markup": "markdown", "html": "<p>Currently there is an error on line 79 in _load_data.py where if genomedata-load is not on your path, python attempts to pipe into a process it cannot find resulting in a \"write error: Broken pipe\" and \"OSError: [Errno 2] No such file or directory\".</p>\n<p>There should be a better error message for this case.</p>", "type": "rendered"}, "assignee": {"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}, "state": "new", "version": null, "edited_on": null, "created_on": "2016-12-15T21:07:49.310399+00:00", "milestone": null, "updated_on": "2016-12-15T21:07:49.310399+00:00", "type": "issue", "id": 28}