{"priority": "minor", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata.json"}, "html": {"href": "#!/hoffmanlab/genomedata"}, "avatar": {"href": "data/bytebucket.org/ravatar/{78038659-1199-46ff-9d0a-675c62f89d60}ts=python"}}, "type": "repository", "name": "genomedata", "full_name": "hoffmanlab/genomedata", "uuid": "{78038659-1199-46ff-9d0a-675c62f89d60}"}, "links": {"attachments": {"href": "data/repositories/hoffmanlab/genomedata/issues/46/attachments_page=1.json"}, "self": {"href": "data/repositories/hoffmanlab/genomedata/issues/46.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/genomedata/issues/46/watch"}, "comments": {"href": "data/repositories/hoffmanlab/genomedata/issues/46/comments_page=1.json"}, "html": {"href": "#!/hoffmanlab/genomedata/issues/46/anaconda-distribution-broken"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/genomedata/issues/46/vote"}}, "reporter": {"display_name": "Kate Cook", "uuid": "{36c88b70-42d6-4662-bde3-2316c4423895}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B36c88b70-42d6-4662-bde3-2316c4423895%7D"}, "html": {"href": "https://bitbucket.org/%7B36c88b70-42d6-4662-bde3-2316c4423895%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/f46c0bafb4d227957572a7f47c9e2980d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsKC-4.png"}}, "nickname": "katecook", "type": "user", "account_id": "557058:499caa63-3f6a-4f40-b404-8fc921427fc9"}, "title": "Anaconda distribution broken", "component": null, "votes": 0, "watches": 1, "content": {"raw": "Hi,\r\n\r\nThe version of genomedata on bioconda doesn't run as-is on my system. It's a problem with the [version of path.py](https://pathpy.readthedocs.io/en/stable/history.html#id44), although I don't know how the requirement of forked-path plays into this.\r\n\r\nIt looks like this was fixed a while ago in genomedata/__init.py__, but the version of genomedata on bioconda is 1.4.1. Any plans to update that soon? I could install from source, but I am lazy :)\r\n\r\nKate\r\n\r\n```\r\n#!bash\r\n\r\n(python2) [hpc4366@caclogin02 ~]$ conda install genomedata\r\nFetching package metadata ...............\r\nSolving package specifications: .\r\n\r\nPackage plan for installation in environment /global/home/hpc4366/.conda/envs/python2:\r\n\r\nThe following NEW packages will be INSTALLED:\r\n\r\n    genomedata: 1.4.1-py27h470a237_2 bioconda\r\n\r\nProceed ([y]/n)? y\r\n\r\n(python2) [hpc4366@caclogin02 ~]$ genomedata-load --version\r\nTraceback (most recent call last):\r\n  File \"/global/home/hpc4366/.conda/envs/python2/bin/genomedata-load\", line 7, in <module>\r\n    from genomedata.load_genomedata import main\r\n  File \"/global/home/hpc4366/.conda/envs/python2/lib/python2.7/site-packages/genomedata/__init__.py\", line 30, in <module>\r\n    from path import path\r\nImportError: cannot import name path\r\n```", "markup": "markdown", "html": "<p>Hi,</p>\n<p>The version of genomedata on bioconda doesn't run as-is on my system. It's a problem with the <a data-is-external-link=\"true\" href=\"https://pathpy.readthedocs.io/en/stable/history.html#id44\" rel=\"nofollow\">version of path.py</a>, although I don't know how the requirement of forked-path plays into this.</p>\n<p>It looks like this was fixed a while ago in genomedata/<strong>init.py</strong>, but the version of genomedata on bioconda is 1.4.1. Any plans to update that soon? I could install from source, but I am lazy :)</p>\n<p>Kate</p>\n<div class=\"codehilite language-bash\"><pre><span></span><span class=\"o\">(</span>python2<span class=\"o\">)</span> <span class=\"o\">[</span>hpc4366@caclogin02 ~<span class=\"o\">]</span>$ conda install genomedata\nFetching package metadata ...............\nSolving package specifications: .\n\nPackage plan <span class=\"k\">for</span> installation in environment /global/home/hpc4366/.conda/envs/python2:\n\nThe following NEW packages will be INSTALLED:\n\n    genomedata: <span class=\"m\">1</span>.4.1-py27h470a237_2 bioconda\n\nProceed <span class=\"o\">([</span>y<span class=\"o\">]</span>/n<span class=\"o\">)</span>? y\n\n<span class=\"o\">(</span>python2<span class=\"o\">)</span> <span class=\"o\">[</span>hpc4366@caclogin02 ~<span class=\"o\">]</span>$ genomedata-load --version\nTraceback <span class=\"o\">(</span>most recent call last<span class=\"o\">)</span>:\n  File <span class=\"s2\">&quot;/global/home/hpc4366/.conda/envs/python2/bin/genomedata-load&quot;</span>, line <span class=\"m\">7</span>, in &lt;module&gt;\n    from genomedata.load_genomedata import main\n  File <span class=\"s2\">&quot;/global/home/hpc4366/.conda/envs/python2/lib/python2.7/site-packages/genomedata/__init__.py&quot;</span>, line <span class=\"m\">30</span>, in &lt;module&gt;\n    from path import path\nImportError: cannot import name path\n</pre></div>", "type": "rendered"}, "assignee": null, "state": "resolved", "version": null, "edited_on": null, "created_on": "2018-10-15T17:41:54.000165+00:00", "milestone": null, "updated_on": "2019-01-21T15:03:33.191398+00:00", "type": "issue", "id": 46}