{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata.json"}, "html": {"href": "#!/hoffmanlab/genomedata"}, "avatar": {"href": "data/bytebucket.org/ravatar/{78038659-1199-46ff-9d0a-675c62f89d60}ts=python"}}, "type": "repository", "name": "genomedata", "full_name": "hoffmanlab/genomedata", "uuid": "{78038659-1199-46ff-9d0a-675c62f89d60}"}, "links": {"attachments": {"href": "data/repositories/hoffmanlab/genomedata/issues/51/attachments_page=1.json"}, "self": {"href": "data/repositories/hoffmanlab/genomedata/issues/51.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/genomedata/issues/51/watch"}, "comments": {"href": "data/repositories/hoffmanlab/genomedata/issues/51/comments_page=1.json"}, "html": {"href": "#!/hoffmanlab/genomedata/issues/51/recent-genomedata-versions-break-previous"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/hoffmanlab/genomedata/issues/51/vote"}}, "reporter": {"display_name": "Coby Viner", "uuid": "{5c0277b2-d18f-432a-9ff0-3377d3063bd6}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B5c0277b2-d18f-432a-9ff0-3377d3063bd6%7D"}, "html": {"href": "https://bitbucket.org/%7B5c0277b2-d18f-432a-9ff0-3377d3063bd6%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/30ee4699432a3591c043fbe3d4bff771d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCV-5.png"}}, "nickname": "cviner2", "type": "user", "account_id": "557058:278c659b-177a-486c-bf20-6982986d7e43"}, "title": "Recent genomedata versions break previous (version 1.3.6) masking", "component": null, "votes": 0, "watches": 1, "content": {"raw": "The following error occurs on the latest version (1.4.4), but works fine in version 1.3.6. It seems like this is due to the new masking functionality, added in 1.4.0.\r\n\r\n```\r\n#!text\r\n\r\n>> <cytomod.py> 2019-01-02T17:18:55.693228 Genomedata archive\r\n                                           successfully loaded.\r\n>> <cytomod.py> 2019-01-02T17:18:55.697772 Masking is enabled. All\r\n                                           loci implicated by the mask\r\n                                           will be masked\r\n                                           irrespective of any mods at\r\n                                           those loci.\r\n>> <cytomod.py> 2019-01-02T17:18:55.697999 The order of preference for\r\n                                           base\r\n                                           modifications (from highest\r\n                                           to lowest) is:\r\n                                           f,h,m,c,w,x,y,z.\r\n>> <cytomod.py> 2019-01-02T17:18:55.700827 Outputting the modified\r\n                                           genome for: chrY\r\n>> <cytomod.py> 2019-01-02T17:18:55.706329 Now outputting chrY for\r\n                                           region: (0, 2000000)\r\nTraceback (most recent call last):\r\n  File \"../../src/cytomod.py\", line 859, in <module>\r\n    args.maskAllUnsetRegions)\r\n  File \"../../src/cytomod.py\", line 313, in generateFASTAFile\r\n    maskAllUnsetRegions) + \"\\n\")\r\n  File \"../../src/cytomod.py\", line 147, in getModifiedGenome\r\n    maskTrack = chromosome[s:e, maskRegionTName]\r\n  File \"/home/cviner2/.local/lib/python2.7/site-packages/genomedata/__init__.py\", line 755, in __getitem__\r\n    track_key)\r\nTypeError: Unrecognized track indexing method: mm9_chrY-only_MASK-cov.bedGraph.gz\r\n```\r\n\r\nIt would be nice if backward compatibility could be restored and preserved.\r\n\r\nPlease find the offending BEDGraph file (`mm9_chrY-only_MASK-cov.bedGraph.gz`) enclosed.", "markup": "markdown", "html": "<p>The following error occurs on the latest version (1.4.4), but works fine in version 1.3.6. It seems like this is due to the new masking functionality, added in 1.4.0.</p>\n<div class=\"codehilite language-text\"><pre><span></span>&gt;&gt; &lt;cytomod.py&gt; 2019-01-02T17:18:55.693228 Genomedata archive\n                                           successfully loaded.\n&gt;&gt; &lt;cytomod.py&gt; 2019-01-02T17:18:55.697772 Masking is enabled. All\n                                           loci implicated by the mask\n                                           will be masked\n                                           irrespective of any mods at\n                                           those loci.\n&gt;&gt; &lt;cytomod.py&gt; 2019-01-02T17:18:55.697999 The order of preference for\n                                           base\n                                           modifications (from highest\n                                           to lowest) is:\n                                           f,h,m,c,w,x,y,z.\n&gt;&gt; &lt;cytomod.py&gt; 2019-01-02T17:18:55.700827 Outputting the modified\n                                           genome for: chrY\n&gt;&gt; &lt;cytomod.py&gt; 2019-01-02T17:18:55.706329 Now outputting chrY for\n                                           region: (0, 2000000)\nTraceback (most recent call last):\n  File &quot;../../src/cytomod.py&quot;, line 859, in &lt;module&gt;\n    args.maskAllUnsetRegions)\n  File &quot;../../src/cytomod.py&quot;, line 313, in generateFASTAFile\n    maskAllUnsetRegions) + &quot;\\n&quot;)\n  File &quot;../../src/cytomod.py&quot;, line 147, in getModifiedGenome\n    maskTrack = chromosome[s:e, maskRegionTName]\n  File &quot;/home/cviner2/.local/lib/python2.7/site-packages/genomedata/__init__.py&quot;, line 755, in __getitem__\n    track_key)\nTypeError: Unrecognized track indexing method: mm9_chrY-only_MASK-cov.bedGraph.gz\n</pre></div>\n\n\n<p>It would be nice if backward compatibility could be restored and preserved.</p>\n<p>Please find the offending BEDGraph file (<code>mm9_chrY-only_MASK-cov.bedGraph.gz</code>) enclosed.</p>", "type": "rendered"}, "assignee": {"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}, "state": "open", "version": null, "edited_on": null, "created_on": "2019-01-02T22:27:47.608907+00:00", "milestone": null, "updated_on": "2019-07-06T18:25:05.710099+00:00", "type": "issue", "id": 51}