{"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/issues/46/comments/48361886.json"}, "html": {"href": "#!/hoffmanlab/genomedata/issues/46#comment-48361886"}}, "issue": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/issues/46.json"}}, "type": "issue", "id": 46, "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata.json"}, "html": {"href": "#!/hoffmanlab/genomedata"}, "avatar": {"href": "data/bytebucket.org/ravatar/{78038659-1199-46ff-9d0a-675c62f89d60}ts=python"}}, "type": "repository", "name": "genomedata", "full_name": "hoffmanlab/genomedata", "uuid": "{78038659-1199-46ff-9d0a-675c62f89d60}"}, "title": "Anaconda distribution broken"}, "content": {"raw": "2. Do you have hdf5 installed somewhere else? That doesn't work for me without an explicit \"module load hdf5\". Anaconda won't modify the include path environment variables so gcc doesn't know to look for the anaconda-installed hdf5.\n\n1. I still get the GLIBC_2.18 error, so I'll ask cac support.", "markup": "markdown", "html": "<ol>\n<li>\n<p>Do you have hdf5 installed somewhere else? That doesn't work for me without an explicit \"module load hdf5\". Anaconda won't modify the include path environment variables so gcc doesn't know to look for the anaconda-installed hdf5.</p>\n</li>\n<li>\n<p>I still get the GLIBC_2.18 error, so I'll ask cac support.</p>\n</li>\n</ol>", "type": "rendered"}, "created_on": "2018-10-15T21:09:26.269090+00:00", "user": {"display_name": "Kate Cook", "uuid": "{36c88b70-42d6-4662-bde3-2316c4423895}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B36c88b70-42d6-4662-bde3-2316c4423895%7D"}, "html": {"href": "https://bitbucket.org/%7B36c88b70-42d6-4662-bde3-2316c4423895%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/f46c0bafb4d227957572a7f47c9e2980d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsKC-4.png"}}, "nickname": "katecook", "type": "user", "account_id": "557058:499caa63-3f6a-4f40-b404-8fc921427fc9"}, "updated_on": null, "type": "issue_comment", "id": 48361886}