{"pagelen": 100, "values": [{"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/issues/46/comments/48359128.json"}, "html": {"href": "#!/hoffmanlab/genomedata/issues/46#comment-48359128"}}, "issue": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/issues/46.json"}}, "type": "issue", "id": 46, "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata.json"}, "html": {"href": "#!/hoffmanlab/genomedata"}, "avatar": {"href": "data/bytebucket.org/ravatar/{78038659-1199-46ff-9d0a-675c62f89d60}ts=python"}}, "type": "repository", "name": "genomedata", "full_name": "hoffmanlab/genomedata", "uuid": "{78038659-1199-46ff-9d0a-675c62f89d60}"}, "title": "Anaconda distribution broken"}, "content": {"raw": "Yep! [The current Bioconda PR](https://github.com/bioconda/bioconda-recipes/pull/11038).\n\nThis is on the top of my todo list currently. Genomedata had some recent small improvements as well so the Bioconda PR is planning a newer Genomedata version and an updated conda recipe.\n\nIt's worth noting that in an empty conda environment, a 'pip install genomedata' should work just fine (in either python 2 or 3) as well. Currently only the conda recipe seems to be broken.", "markup": "markdown", "html": "<p>Yep! <a data-is-external-link=\"true\" href=\"https://github.com/bioconda/bioconda-recipes/pull/11038\" rel=\"nofollow\">The current Bioconda PR</a>.</p>\n<p>This is on the top of my todo list currently. Genomedata had some recent small improvements as well so the Bioconda PR is planning a newer Genomedata version and an updated conda recipe.</p>\n<p>It's worth noting that in an empty conda environment, a 'pip install genomedata' should work just fine (in either python 2 or 3) as well. Currently only the conda recipe seems to be broken.</p>", "type": "rendered"}, "created_on": "2018-10-15T17:48:46.053030+00:00", "user": {"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}, "updated_on": "2018-10-15T17:49:59.729686+00:00", "type": "issue_comment", "id": 48359128}, {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/issues/46/comments/48359209.json"}, "html": {"href": "#!/hoffmanlab/genomedata/issues/46#comment-48359209"}}, "issue": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/issues/46.json"}}, "type": "issue", "id": 46, "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata.json"}, "html": {"href": "#!/hoffmanlab/genomedata"}, "avatar": {"href": "data/bytebucket.org/ravatar/{78038659-1199-46ff-9d0a-675c62f89d60}ts=python"}}, "type": "repository", "name": "genomedata", "full_name": "hoffmanlab/genomedata", "uuid": "{78038659-1199-46ff-9d0a-675c62f89d60}"}, "title": "Anaconda distribution broken"}, "content": {"raw": "Great, thanks. P.S. I saw elsewhere that you were working on SLURM support for segway which would also be very helpful for me. Happy to test things out.", "markup": "markdown", "html": "<p>Great, thanks. P.S. I saw elsewhere that you were working on SLURM support for segway which would also be very helpful for me. Happy to test things out.</p>", "type": "rendered"}, "created_on": "2018-10-15T17:52:04.547979+00:00", "user": {"display_name": "Kate Cook", "uuid": "{36c88b70-42d6-4662-bde3-2316c4423895}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B36c88b70-42d6-4662-bde3-2316c4423895%7D"}, "html": {"href": "https://bitbucket.org/%7B36c88b70-42d6-4662-bde3-2316c4423895%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/f46c0bafb4d227957572a7f47c9e2980d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsKC-4.png"}}, "nickname": "katecook", "type": "user", "account_id": "557058:499caa63-3f6a-4f40-b404-8fc921427fc9"}, "updated_on": null, "type": "issue_comment", "id": 48359209}, {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/issues/46/comments/48360077.json"}, "html": {"href": "#!/hoffmanlab/genomedata/issues/46#comment-48360077"}}, "issue": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/issues/46.json"}}, "type": "issue", "id": 46, "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata.json"}, "html": {"href": "#!/hoffmanlab/genomedata"}, "avatar": {"href": "data/bytebucket.org/ravatar/{78038659-1199-46ff-9d0a-675c62f89d60}ts=python"}}, "type": "repository", "name": "genomedata", "full_name": "hoffmanlab/genomedata", "uuid": "{78038659-1199-46ff-9d0a-675c62f89d60}"}, "title": "Anaconda distribution broken"}, "content": {"raw": "pip install genomedata doesn't work either:\n\n\n```\n#!shell\n(python3) [hpc4366@caclogin02 dev]$ pip install genomedata\nLooking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic\nCollecting genomedata\n  Using cached https://files.pythonhosted.org/packages/ae/a8/095d15019a28d370b0f81a5adb289828dee17b5ac5e069518024526996f6/genomedata-1.4.4.tar.gz\nRequirement already satisfied: numpy in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages (from genomedata) (1.15.0)\nRequirement already satisfied: tables!=3.4.1,>=3.0 in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages (from genomedata) (3.4.4)\nRequirement already satisfied: six in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages (from genomedata) (1.11.0)\nRequirement already satisfied: textinput>=0.2.0 in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages (from genomedata) (0.2.0)\nRequirement already satisfied: path.py>=11 in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages (from genomedata) (11.5.0)\nRequirement already satisfied: numexpr>=2.5.2 in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages (from tables!=3.4.1,>=3.0->genomedata) (2.6.8)\nRequirement already satisfied: importlib-metadata>=0.5 in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages (from path.py>=11->genomedata) (0.6)\nBuilding wheels for collected packages: genomedata\n  Running setup.py bdist_wheel for genomedata ... done\n  Stored in directory: /global/home/hpc4366/.cache/pip/wheels/ca/cf/32/223bb7e516403ed63d3f492870accb7dc54cb601e3f745d3b6\nSuccessfully built genomedata\nInstalling collected packages: genomedata\nSuccessfully installed genomedata-1.4.4\n(python3) [hpc4366@caclogin02 dev]$ genomedata-load --version\nTraceback (most recent call last):\n  File \"/global/home/hpc4366/.conda/envs/python3/bin/genomedata-load\", line 7, in <module>\n    from genomedata.load_genomedata import main\n  File \"/global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages/genomedata/__init__.py\", line 28, in <module>\n    import tables\n  File \"/global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages/tables/__init__.py\", line 93, in <module>\n    from .utilsextension import (\nImportError: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-5.4.0/lib64/libstdc++.so.6)\n\n```\n\n(I switched to python 3 here but python 2 fails as well with an even more cryptic error)", "markup": "markdown", "html": "<p>pip install genomedata doesn't work either:</p>\n<div class=\"codehilite language-shell\"><pre><span></span><span class=\"o\">(</span>python3<span class=\"o\">)</span> <span class=\"o\">[</span>hpc4366@caclogin02 dev<span class=\"o\">]</span>$ pip install genomedata\nLooking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic\nCollecting genomedata\n  Using cached https://files.pythonhosted.org/packages/ae/a8/095d15019a28d370b0f81a5adb289828dee17b5ac5e069518024526996f6/genomedata-1.4.4.tar.gz\nRequirement already satisfied: numpy in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages <span class=\"o\">(</span>from genomedata<span class=\"o\">)</span> <span class=\"o\">(</span><span class=\"m\">1</span>.15.0<span class=\"o\">)</span>\nRequirement already satisfied: tables!<span class=\"o\">=</span><span class=\"m\">3</span>.4.1,&gt;<span class=\"o\">=</span><span class=\"m\">3</span>.0 in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages <span class=\"o\">(</span>from genomedata<span class=\"o\">)</span> <span class=\"o\">(</span><span class=\"m\">3</span>.4.4<span class=\"o\">)</span>\nRequirement already satisfied: six in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages <span class=\"o\">(</span>from genomedata<span class=\"o\">)</span> <span class=\"o\">(</span><span class=\"m\">1</span>.11.0<span class=\"o\">)</span>\nRequirement already satisfied: textinput&gt;<span class=\"o\">=</span><span class=\"m\">0</span>.2.0 in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages <span class=\"o\">(</span>from genomedata<span class=\"o\">)</span> <span class=\"o\">(</span><span class=\"m\">0</span>.2.0<span class=\"o\">)</span>\nRequirement already satisfied: path.py&gt;<span class=\"o\">=</span><span class=\"m\">11</span> in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages <span class=\"o\">(</span>from genomedata<span class=\"o\">)</span> <span class=\"o\">(</span><span class=\"m\">11</span>.5.0<span class=\"o\">)</span>\nRequirement already satisfied: numexpr&gt;<span class=\"o\">=</span><span class=\"m\">2</span>.5.2 in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages <span class=\"o\">(</span>from tables!<span class=\"o\">=</span><span class=\"m\">3</span>.4.1,&gt;<span class=\"o\">=</span><span class=\"m\">3</span>.0-&gt;genomedata<span class=\"o\">)</span> <span class=\"o\">(</span><span class=\"m\">2</span>.6.8<span class=\"o\">)</span>\nRequirement already satisfied: importlib-metadata&gt;<span class=\"o\">=</span><span class=\"m\">0</span>.5 in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages <span class=\"o\">(</span>from path.py&gt;<span class=\"o\">=</span><span class=\"m\">11</span>-&gt;genomedata<span class=\"o\">)</span> <span class=\"o\">(</span><span class=\"m\">0</span>.6<span class=\"o\">)</span>\nBuilding wheels <span class=\"k\">for</span> collected packages: genomedata\n  Running setup.py bdist_wheel <span class=\"k\">for</span> genomedata ... <span class=\"k\">done</span>\n  Stored in directory: /global/home/hpc4366/.cache/pip/wheels/ca/cf/32/223bb7e516403ed63d3f492870accb7dc54cb601e3f745d3b6\nSuccessfully built genomedata\nInstalling collected packages: genomedata\nSuccessfully installed genomedata-1.4.4\n<span class=\"o\">(</span>python3<span class=\"o\">)</span> <span class=\"o\">[</span>hpc4366@caclogin02 dev<span class=\"o\">]</span>$ genomedata-load --version\nTraceback <span class=\"o\">(</span>most recent call last<span class=\"o\">)</span>:\n  File <span class=\"s2\">&quot;/global/home/hpc4366/.conda/envs/python3/bin/genomedata-load&quot;</span>, line <span class=\"m\">7</span>, in &lt;module&gt;\n    from genomedata.load_genomedata import main\n  File <span class=\"s2\">&quot;/global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages/genomedata/__init__.py&quot;</span>, line <span class=\"m\">28</span>, in &lt;module&gt;\n    import tables\n  File <span class=\"s2\">&quot;/global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages/tables/__init__.py&quot;</span>, line <span class=\"m\">93</span>, in &lt;module&gt;\n    from .utilsextension import <span class=\"o\">(</span>\nImportError: /lib64/libc.so.6: version <span class=\"sb\">`</span>GLIBC_2.18<span class=\"err\">&#39;</span> not found <span class=\"o\">(</span>required by /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-5.4.0/lib64/libstdc++.so.6<span class=\"o\">)</span>\n</pre></div>\n\n\n<p>(I switched to python 3 here but python 2 fails as well with an even more cryptic error)</p>", "type": "rendered"}, "created_on": "2018-10-15T18:40:15.905474+00:00", "user": {"display_name": "Kate Cook", "uuid": "{36c88b70-42d6-4662-bde3-2316c4423895}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B36c88b70-42d6-4662-bde3-2316c4423895%7D"}, "html": {"href": "https://bitbucket.org/%7B36c88b70-42d6-4662-bde3-2316c4423895%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/f46c0bafb4d227957572a7f47c9e2980d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsKC-4.png"}}, "nickname": "katecook", "type": "user", "account_id": "557058:499caa63-3f6a-4f40-b404-8fc921427fc9"}, "updated_on": null, "type": "issue_comment", "id": 48360077}, {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/issues/46/comments/48360530.json"}, "html": {"href": "#!/hoffmanlab/genomedata/issues/46#comment-48360530"}}, "issue": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/issues/46.json"}}, "type": "issue", "id": 46, "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata.json"}, "html": {"href": "#!/hoffmanlab/genomedata"}, "avatar": {"href": "data/bytebucket.org/ravatar/{78038659-1199-46ff-9d0a-675c62f89d60}ts=python"}}, "type": "repository", "name": "genomedata", "full_name": "hoffmanlab/genomedata", "uuid": "{78038659-1199-46ff-9d0a-675c62f89d60}"}, "title": "Anaconda distribution broken"}, "content": {"raw": "That looks like a problem with your configuration unfortunately. The requirement of GLIBC_2.18 is coming from your system configuration. I would ask the Compute Canada helpdesk, they are fast.", "markup": "markdown", "html": "<p>That looks like a problem with your configuration unfortunately. The requirement of GLIBC_2.18 is coming from your system configuration. I would ask the Compute Canada helpdesk, they are fast.</p>", "type": "rendered"}, "created_on": "2018-10-15T19:09:46.055306+00:00", "user": {"display_name": "Michael Hoffman", "uuid": "{ffa8e039-5d4d-4f69-a4ba-ac25cbaf700b}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bffa8e039-5d4d-4f69-a4ba-ac25cbaf700b%7D"}, "html": {"href": "https://bitbucket.org/%7Bffa8e039-5d4d-4f69-a4ba-ac25cbaf700b%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/6a95e857a02504cbad5fe965c9d9e4bbd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsMH-1.png"}}, "nickname": "hoffman", "type": "user", "account_id": "557058:a9657985-692c-405c-995b-4e41cda7ba2b"}, "updated_on": null, "type": "issue_comment", "id": 48360530}, {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/issues/46/comments/48360715.json"}, "html": {"href": "#!/hoffmanlab/genomedata/issues/46#comment-48360715"}}, "issue": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/issues/46.json"}}, "type": "issue", "id": 46, "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata.json"}, "html": {"href": "#!/hoffmanlab/genomedata"}, "avatar": {"href": "data/bytebucket.org/ravatar/{78038659-1199-46ff-9d0a-675c62f89d60}ts=python"}}, "type": "repository", "name": "genomedata", "full_name": "hoffmanlab/genomedata", "uuid": "{78038659-1199-46ff-9d0a-675c62f89d60}"}, "title": "Anaconda distribution broken"}, "content": {"raw": "Just a heads up since it indeed seems like a strange environment issue - there are two things note here:\n\n1. It looks like it's related spcifically to Pytables, since it crashes after an \"import tables\" and specifically importing one of its c-built extensions. \n2. I cannot reproduce this on Niagra (Compute Canada). The following works for me:\n```shell\n$ module load anaconda3\n# Add bioconda channels if you have not already\n$ conda create -n python3 python=3 hdf5\n$ source activate python3\n$ pip install genomedata\n$ genomedata-load --version\n```", "markup": "markdown", "html": "<p>Just a heads up since it indeed seems like a strange environment issue - there are two things note here:</p>\n<ol>\n<li>It looks like it's related spcifically to Pytables, since it crashes after an \"import tables\" and specifically importing one of its c-built extensions. </li>\n<li>I cannot reproduce this on Niagra (Compute Canada). The following works for me:</li>\n</ol>\n<div class=\"codehilite language-shell\"><pre><span></span>$ module load anaconda3\n<span class=\"c1\"># Add bioconda channels if you have not already</span>\n$ conda create -n python3 <span class=\"nv\">python</span><span class=\"o\">=</span><span class=\"m\">3</span> hdf5\n$ <span class=\"nb\">source</span> activate python3\n$ pip install genomedata\n$ genomedata-load --version\n</pre></div>", "type": "rendered"}, "created_on": "2018-10-15T19:25:23.061876+00:00", "user": {"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}, "updated_on": null, "type": "issue_comment", "id": 48360715}, {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/issues/46/comments/48361886.json"}, "html": {"href": "#!/hoffmanlab/genomedata/issues/46#comment-48361886"}}, "issue": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/issues/46.json"}}, "type": "issue", "id": 46, "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata.json"}, "html": {"href": "#!/hoffmanlab/genomedata"}, "avatar": {"href": "data/bytebucket.org/ravatar/{78038659-1199-46ff-9d0a-675c62f89d60}ts=python"}}, "type": "repository", "name": "genomedata", "full_name": "hoffmanlab/genomedata", "uuid": "{78038659-1199-46ff-9d0a-675c62f89d60}"}, "title": "Anaconda distribution broken"}, "content": {"raw": "2. Do you have hdf5 installed somewhere else? That doesn't work for me without an explicit \"module load hdf5\". Anaconda won't modify the include path environment variables so gcc doesn't know to look for the anaconda-installed hdf5.\n\n1. I still get the GLIBC_2.18 error, so I'll ask cac support.", "markup": "markdown", "html": "<ol>\n<li>\n<p>Do you have hdf5 installed somewhere else? That doesn't work for me without an explicit \"module load hdf5\". Anaconda won't modify the include path environment variables so gcc doesn't know to look for the anaconda-installed hdf5.</p>\n</li>\n<li>\n<p>I still get the GLIBC_2.18 error, so I'll ask cac support.</p>\n</li>\n</ol>", "type": "rendered"}, "created_on": "2018-10-15T21:09:26.269090+00:00", "user": {"display_name": "Kate Cook", "uuid": "{36c88b70-42d6-4662-bde3-2316c4423895}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B36c88b70-42d6-4662-bde3-2316c4423895%7D"}, "html": {"href": "https://bitbucket.org/%7B36c88b70-42d6-4662-bde3-2316c4423895%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/f46c0bafb4d227957572a7f47c9e2980d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsKC-4.png"}}, "nickname": "katecook", "type": "user", "account_id": "557058:499caa63-3f6a-4f40-b404-8fc921427fc9"}, "updated_on": null, "type": "issue_comment", "id": 48361886}, {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/issues/46/comments/48374727.json"}, "html": {"href": "#!/hoffmanlab/genomedata/issues/46#comment-48374727"}}, "issue": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/issues/46.json"}}, "type": "issue", "id": 46, "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata.json"}, "html": {"href": "#!/hoffmanlab/genomedata"}, "avatar": {"href": "data/bytebucket.org/ravatar/{78038659-1199-46ff-9d0a-675c62f89d60}ts=python"}}, "type": "repository", "name": "genomedata", "full_name": "hoffmanlab/genomedata", "uuid": "{78038659-1199-46ff-9d0a-675c62f89d60}"}, "title": "Anaconda distribution broken"}, "content": {"raw": "The line:\n`$ conda create -n python3 python=3 hdf5` should install HDF5 in the conda environment named \"python3\". I did not install HDF5 is any other way or load it through a module.\n\nI'd imagine there's likely some conflict between your loaded modules and the conda environment itself. I had no other modules explictly loaded except \"anaconda3\".", "markup": "markdown", "html": "<p>The line:\n<code>$ conda create -n python3 python=3 hdf5</code> should install HDF5 in the conda environment named \"python3\". I did not install HDF5 is any other way or load it through a module.</p>\n<p>I'd imagine there's likely some conflict between your loaded modules and the conda environment itself. I had no other modules explictly loaded except \"anaconda3\".</p>", "type": "rendered"}, "created_on": "2018-10-16T12:57:58.798472+00:00", "user": {"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}, "updated_on": null, "type": "issue_comment", "id": 48374727}, {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/issues/46/comments/48381431.json"}, "html": {"href": "#!/hoffmanlab/genomedata/issues/46#comment-48381431"}}, "issue": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/issues/46.json"}}, "type": "issue", "id": 46, "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata.json"}, "html": {"href": "#!/hoffmanlab/genomedata"}, "avatar": {"href": "data/bytebucket.org/ravatar/{78038659-1199-46ff-9d0a-675c62f89d60}ts=python"}}, "type": "repository", "name": "genomedata", "full_name": "hoffmanlab/genomedata", "uuid": "{78038659-1199-46ff-9d0a-675c62f89d60}"}, "title": "Anaconda distribution broken"}, "content": {"raw": "Anaconda doesn't set LD_LIBRARY_PATH  or C_INCLUDE_PATH though. (I looked at this issue earlier: #!/hoffmanlab/genomedata/issues/15/install-fails-with-anaconda-python )", "markup": "markdown", "html": "<p>Anaconda doesn't set LD_LIBRARY_PATH  or C_INCLUDE_PATH though. (I looked at this issue earlier: <a href=\"#!/hoffmanlab/genomedata/issues/15/install-fails-with-anaconda-python\" rel=\"nofollow\" class=\"ap-connect-link\">#!/hoffmanlab/genomedata/issues/15/install-fails-with-anaconda-python</a> )</p>", "type": "rendered"}, "created_on": "2018-10-16T16:05:56.926813+00:00", "user": {"display_name": "Kate Cook", "uuid": "{36c88b70-42d6-4662-bde3-2316c4423895}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B36c88b70-42d6-4662-bde3-2316c4423895%7D"}, "html": {"href": "https://bitbucket.org/%7B36c88b70-42d6-4662-bde3-2316c4423895%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/f46c0bafb4d227957572a7f47c9e2980d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsKC-4.png"}}, "nickname": "katecook", "type": "user", "account_id": "557058:499caa63-3f6a-4f40-b404-8fc921427fc9"}, "updated_on": null, "type": "issue_comment", "id": 48381431}, {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/issues/46/comments/50137127.json"}, "html": {"href": "#!/hoffmanlab/genomedata/issues/46#comment-50137127"}}, "issue": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/issues/46.json"}}, "type": "issue", "id": 46, "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata.json"}, "html": {"href": "#!/hoffmanlab/genomedata"}, "avatar": {"href": "data/bytebucket.org/ravatar/{78038659-1199-46ff-9d0a-675c62f89d60}ts=python"}}, "type": "repository", "name": "genomedata", "full_name": "hoffmanlab/genomedata", "uuid": "{78038659-1199-46ff-9d0a-675c62f89d60}"}, "title": "Anaconda distribution broken"}, "content": {"raw": "Genomedata 1.4.4 is now available through the Bioconda channel.\n\nMost of the issues fixed were not from Genomedata itself but conda environment and build issues upstream:\n\n- [PyTables including out-of-date zlib symbols in their conda build and not using the zlib in the environment](https://github.com/conda-forge/pytables-feedstock/issues/41)\n- [Genomedata errenously wrapping function calls inside asserts which were optimized out in the conda build](#!/hoffmanlab/genomedata/issues/47/assert-statements-from)\n- [Conda-forge dropping support for Python 3.5 in October 2018 and Bioconda still using Python 3.5 result in using out-of-date conda-forge packages for the Python 3.5 Bioconda build](https://github.com/bioconda/bioconda-recipes/issues/13097)\n\nAll issues above have been fixed or worked around for the conda build. However we cannot support Python 3.5 since conda-forge will no longer include our upstream fixes. Also as mentioned above the current Bioconda build system does not build for Python 3.7. So unfortunately for Python 3 the only option available is Python 3.6 for installation. Do not use a conda environment with Python 3.5 if at all possible with Genomedata. It has some really subtle and nasty environment issues and will break.\n\ncc @katecook", "markup": "markdown", "html": "<p>Genomedata 1.4.4 is now available through the Bioconda channel.</p>\n<p>Most of the issues fixed were not from Genomedata itself but conda environment and build issues upstream:</p>\n<ul>\n<li><a data-is-external-link=\"true\" href=\"https://github.com/conda-forge/pytables-feedstock/issues/41\" rel=\"nofollow\">PyTables including out-of-date zlib symbols in their conda build and not using the zlib in the environment</a></li>\n<li><a data-is-external-link=\"true\" href=\"#!/hoffmanlab/genomedata/issues/47/assert-statements-from\" rel=\"nofollow\">Genomedata errenously wrapping function calls inside asserts which were optimized out in the conda build</a></li>\n<li><a data-is-external-link=\"true\" href=\"https://github.com/bioconda/bioconda-recipes/issues/13097\" rel=\"nofollow\">Conda-forge dropping support for Python 3.5 in October 2018 and Bioconda still using Python 3.5 result in using out-of-date conda-forge packages for the Python 3.5 Bioconda build</a></li>\n</ul>\n<p>All issues above have been fixed or worked around for the conda build. However we cannot support Python 3.5 since conda-forge will no longer include our upstream fixes. Also as mentioned above the current Bioconda build system does not build for Python 3.7. So unfortunately for Python 3 the only option available is Python 3.6 for installation. Do not use a conda environment with Python 3.5 if at all possible with Genomedata. It has some really subtle and nasty environment issues and will break.</p>\n<p>cc @katecook</p>", "type": "rendered"}, "created_on": "2019-01-21T15:03:33.241199+00:00", "user": {"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}, "updated_on": null, "type": "issue_comment", "id": 50137127}], "page": 1, "size": 9}